version: '3.8'

services:

  backend:
    build: .
    command: [ "python", "app/main.py" ]
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
